spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=3776
spring.jpa.hibernate.ddl-auto=update
server.port=8081
jwt.secret=maCleSecreteTresLonguePourJwt2026ProjetPFE
jwt.expiration=86400000
# Dans src/main/resources/application.properties
upload.path=C:/PFE_Reclamation_Intelligente/uploads