# Profil DEVELOPPEMENT ? actif par defaut en local
# Active avec : mvn spring-boot:run (aucun argument necessaire, c'est le defaut)
# ou explicitement : --spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs detailles utiles en developpement
logging.level.com.pfe.backend=DEBUG
logging.level.org.springframework.security=INFO

# Les requetes JPA declenchees pendant le rendu des vues sont acceptables en dev
spring.jpa.open-in-view=true