spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=3776
spring.jpa.hibernate.ddl-auto=update
server.port=8085